CREATE DATABASE $(DB_DATABASE);
GO
CREATE LOGIN $(DB_USERNAME) WITH PASSWORD = '$(DB_PASSWORD)';
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [$(DB_USERNAME)];
GO
USE $(DB_DATABASE);
GO
CREATE USER $(DB_USERNAME) for login $(DB_USERNAME);
GO
GRANT CONTROL ON DATABASE::$(DB_DATABASE) TO $(DB_USERNAME) WITH GRANT OPTION;
GO
CREATE SCHEMA $(DB_SCHEMA)
GO
ALTER USER $(DB_USERNAME) WITH DEFAULT_SCHEMA = $(DB_SCHEMA)
GO







